name: Cypress Tests with Percy

on:
  workflow_dispatch:  # Manual trigger

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Start Percy agent
        run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
